### ISSUE TITLE
How to handle labels when using dark theme with jupyterlabs?

### ISSUE THREAD

**Issue by CptanPanic** [matplotlib/jupyter-matplotlib#25] opened 2017-10-29 20:25 UTC
Hello I am using JupyterLabs and it works great, but a problem I have is when I generate matplot plots() I can't see the text as I use JupyterLabs in dark theme mode, but it seems that the plots are made with black text and transparent background so I can't see labels, etc.  Is there a way to override text color?

**Comment by blink1073** [comment] 2017-10-30 10:36
You can use a [style sheet](https://matplotlib.org/users/style_sheets.html), but it looks like styles don't affect plot titles, so those have to be set manually:

```python
%matplotlib ipympl
import matplotlib.pyplot as plt
plt.style.use(['dark_background'])
plt.plot([0,1,12])
plt.gca().set_title('my title', color='w')
```

![image](https://user-images.githubusercontent.com/2096628/32166553-3b0a8258-bd34-11e7-9764-35a00cd43eeb.png)

**Comment by blink1073** [comment] 2017-10-30 10:42
Actually, we still have a problem with the figure title:

![image](https://user-images.githubusercontent.com/2096628/32166836-1a98b0ca-bd35-11e7-8a89-ad020fb60929.png)

**Comment by blink1073** [comment] 2017-10-30 10:48
Yeah the problem isn't the style sheet, it is our rendered title:

![image](https://user-images.githubusercontent.com/2096628/32167107-f056e718-bd35-11e7-8a52-27658b0c547f.png)

**Comment by lavajiit** [comment] 2018-08-09 16:40
1. We can use following for changing background:-
`plt.patch.set_facecolor('lightgrey')`
But this will work only for single plot. Not for grid plot, or more than one.

2. We can use following for getting graphs like we get in jupyter lab light theme:-
`import matplotlib.pyplot as plt`
`from matplotlib import style`
`style.use('ggplot') or plt.style.use('ggplot')`
We need to specify "style.use('ggplot')" again in any next cell and not in the cell where we first set the style. Yes, we need to set it 2 times. Second should be the lighter theme.
![screenshot from 2018-08-09 21-57-01 01](https://user-images.githubusercontent.com/29814072/43912804-f0f89b88-9c20-11e8-9306-51c1b9fae912.png)


`style.available or plt.style.available`
`['Solarize_Light2',`
` 'grayscale',`
 `'ggplot',`
` 'seaborn-dark-palette',`
` 'seaborn-poster',`
` 'tableau-colorblind10',`
` 'seaborn-ticks',`
` 'seaborn-muted',`
` 'seaborn-bright',`
` '_classic_test',`
` 'seaborn-darkgrid',`
` 'seaborn-paper',`
` 'seaborn',`
` 'seaborn-colorblind',`
` 'classic',`
` 'seaborn-talk',`
` 'seaborn-notebook',`
` 'seaborn-dark',`
` 'fivethirtyeight',`
` 'fast',`
` 'bmh',`
` 'seaborn-pastel',`
` 'seaborn-deep',`
` 'seaborn-white',`
` 'seaborn-whitegrid'`
` 'dark_background']`

lighter ones are:
`
{0: 'Solarize_Light2',
 1: 'grayscale',
 2: 'ggplot',
 6: 'seaborn-ticks',
 9: '_classic_test',
 10: 'seaborn-darkgrid',
 12: 'seaborn',
 14: 'classic',
 17: 'seaborn-dark',
 18: 'fivethirtyeight',
 23: 'seaborn-white',
 24: 'seaborn-whitegrid'}`

darker ones are:
`
{3: 'seaborn-dark-palette',
 4: 'seaborn-poster',
 5: 'tableau-colorblind10',
 7: 'seaborn-muted',
 8: 'seaborn-bright',
 11: 'seaborn-paper',
 13: 'seaborn-colorblind',
 15: 'seaborn-talk',
 16: 'seaborn-notebook',
 19: 'fast',
 20: 'bmh',
 21: 'seaborn-pastel',
 22: 'seaborn-deep',
 25: 'dark_background'}`

**Comment by lavajiit** [comment] 2019-01-23 11:06
Its no more a problem now...perhaps today onwards.
Just update your concerned python libraries(specially jupyterlab):-
`pip install --upgrade numpy pandas matplotlib seaborn jupyterlab`
![git](https://user-images.githubusercontent.com/29814072/51602458-08044e00-1f2d-11e9-8269-fa601b6fb04b.png)

**Comment by SylvainCorlay** [comment] 2019-06-28 14:37
Closing since the jlab theme cannot set the matplotlib style.

However, in master, the toolbar now uses the JupyterLab CSS variables.

**Closed by SylvainCorlay** 2019-06-28 14:37 UTC

**Comment by Psp29onetwo** [comment] 2021-11-30 14:32
I found one solution for expanding the plot canvas a bit so that x and y ticks will get visible.

You need to add one line `plt.style.use('default')` after importing the matplot lib module in notebook.


<img src="https://i.stack.imgur.com/eIc32.png">

See my ticks are outside the canvas before.

<img src="https://i.stack.imgur.com/Yd7LZ.png">

After adding the line the tick got added to the canvas itself no further modification was needed.

<img src="https://i.stack.imgur.com/jNeEg.png">

As you can see in the above image this will pull the x and y ticks in the canvas to make it visible without changing or modifying ticks or plot color, it will make it easier to collaborate your work with others.


  [1]: https://i.stack.imgur.com/eIc32.png
  [2]: https://i.stack.imgur.com/Yd7LZ.png
