### ISSUE TITLE
"Error creating widget: could not find model" after reloading notebook

### ISSUE THREAD

**Issue by mflevine** [matplotlib/jupyter-matplotlib#38] opened 2018-02-02 01:39 UTC
If I reload a notebook after having run a plot, instead of displaying the plot I just see "Error creating widget: could not find model".
![image](https://user-images.githubusercontent.com/15380608/35712418-f66bec8a-078f-11e8-8354-5347bec49191.png)

**Comment by thomasaarholt** [comment] 2018-02-02 10:22
I believe you mean that if you close and reopen the notebook (in jupyter lab), you get the above error. I can reproduce. There is a discussion in #16 that you can follow. This is essentially a duplicate of that issue.

For others (it's always nice to include the code so that we don't have to type it out like I just did):
```python
%matplotlib ipympl
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2*np.pi*t)
plt.plot(t,s)
plt.show()
```

**Closed** 2018-02-02 14:49 UTC
