### ISSUE TITLE
Jupyter Lab idle/busy status is changed for every mouse movement in Jupyter Lab, overwhelming the server

### ISSUE THREAD

**Issue by kboone** [matplotlib/jupyter-matplotlib#144] opened 2019-10-24 18:54 UTC
Version: jupyter-matplotlib 0.3.3 and JupyterLab version 1.1.4

In JupyterLab, whenever the mouse crosses over the canvas it sends a message to the server with the new coordinates every ~5 ms. For each message, the server responds with status update to busy message, a message to update the text, and a status update to idle message. It also updates the favicon, which seems to be causing more network requests (that are probably cached?) Needless to say, this completely overwhelms the server and leads to a lot of lag, even when running on a local machine.

There are two problems here: first, does it make sense to rate limit these update messages somehow?

Second, should there be some kind of timeout to prevent the kernel from flipping between busy/idle this fast? This might be something that needs to happen upstream in Jupyter Lab itself.

**Comment by kboone** [comment] 2019-10-24 22:34
I think that this is just a symptom of a more fundamental issue. Looking at the WebSocket log in chrome, whenever the mouse crosses over the canvas it sends a message to the server with the new coordinates every ~5 ms. For each message, the server responds with status update to busy message, a message to update the text, and a status update to idle message. Needless to say, this completely overwhelms the server and leads to a lot of lag, even when running on a local machine.

There are two problems here: first, does it make sense to rate limit these update messages somehow?

Second, should there be some kind of timeout to prevent the kernel from flipping between busy/idle this fast? This might be something that needs to happen upstream in Jupyter Lab itself.

**Comment by kboone** [comment] 2019-10-24 22:54
I submitted PR #146 which limits these requests to every 40 ms and significantly improves performance. This does not address the rapid busy/idle flipping though.

**Comment by thomasaarholt** [comment] 2019-10-25 13:05
Why does the server need informing of the mouse position? Shouldn't responses like "current cursor coordinates" be handled on the client side? For what other purpose is this it needed? I guess there may be "hover" mechanisms in matplotlib that I'm not aware of, where the server needs updating?

**Comment by SylvainCorlay** [comment] 2019-10-25 13:07
The entire rendering of figures is done in the backend. You can make mpl figures that react to mouse events.

**Comment by SylvainCorlay** [comment] 2019-10-25 13:10
The kernel busy/idle status changing upon every mouse move is expected behavior.

**Comment by thomasaarholt** [comment] 2019-10-25 13:11
Cool, that's fine then. I guess then one has to choose a compromise like @kboone does in #146. Are there standards for the expected update frequency? Is 40ms an "okay" refresh rate?

**Comment by SylvainCorlay** [comment] 2019-10-25 13:11
I am closing the issue as the OP implemented some throttling of messages.

**Closed by SylvainCorlay** 2019-10-25 13:11 UTC

**Comment by SylvainCorlay** [comment] 2019-10-25 15:55
> Are there standards for the expected update frequency? Is 40ms an "okay" refresh rate?

We could make it configurable but a natural rate may be 60fps (~16ms) which is the rate of the browser.

**Comment by kboone** [comment] 2019-10-25 16:52
I played with a few different values, and my browser can barely keep up at 40 ms with Jupyter Lab running locally. A lot of the overhead is flipping the kernel busy/idle status as three messages need to come back from the server for every message sent from the client. For a 16 ms delay, when continuously moving the mouse, I am close to maxing out the CPU on a modern machine (Intel i7-8565) and the server responses become significantly delayed. I think that the favicon changing has a fairly high overhead as the performance is somewhat better in Jupyter Notebook.

It doesn't really make sense to have Jupyter flip between busy/idle for every single request on the client side as this just causes the favicon and the busy/idle indicators to flicker. This adds a huge overhead to any fast operation (like this one). I suggest implementing throttling in the Jupyter server on the busy/idle status updates directly. For example, the server could still keep proper track of its state, but the client would only be taken out of busy mode if there has been no activity in the last 100 ms. This behavior would appear more natural: the busy indicator would be lit throughout the mouse movements rather than flickering continuously.

**Comment by SylvainCorlay** [comment] 2019-10-25 16:58
I understand the reasoning although kernel busy/idle status messages are required by the protocol. I don't think updating the status indicator in the frontend is responsible for the CPU usage though. I suspect the way the message is handled by matplotlib in the backend would be more likely to use resources.

**Comment by kboone** [comment] 2019-10-25 17:34
I played around with this a bit, with both local and remote servers, and it looks like both the frontend and backend have high CPU usage. I agree that any changes to the busy/idle status messages are beyond the scope of this repository and not something that can be easily changed.

It probably doesn't matter too much if the CPU is maxed out for the small amount of time that users are hovering over plots, so a 16 ms delay is probably fine for now.

**Comment by SylvainCorlay** [comment] 2019-10-25 17:38
I left the 40ms. The 16ms was just me answering on whether there was a natural number.

Could as well be 42 :-)

**Comment by kboone** [comment] 2019-10-30 18:45
After playing around with this, 25 fps (40 ms) does feel kind of sluggish. I submitted PR #149 to change this to 60 fps which I think is a better compromise.
